"""baseline

Revision ID: 0001
Revises: 
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journey_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journey_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journey_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_journey_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_journey_events_user_id'), ['user_id'], unique=False)

    op.create_table('llm_usage',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_write_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_llm_usage_user_id'), ['user_id'], unique=False)

    op.create_table('story_feedback',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('story_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_story_feedback_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_story_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('topic_sentence', sa.Text(), nullable=True),
    sa.Column('target_length', sa.String(length=10), nullable=True),
    sa.Column('sequence_pattern', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('card_offered_stage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("sequence_pattern IS NULL OR sequence_pattern IN ('linear', 'return', 'frame', 'cross')", name='ck_sessions_sequence_pattern'),
    sa.CheckConstraint("status IN ('active', 'paused', 'done')", name='ck_sessions_status'),
    sa.CheckConstraint("target_length IS NULL OR target_length IN ('short', 'medium', 'long')", name='ck_sessions_target_length'),
    sa.CheckConstraint('stage BETWEEN 1 AND 4', name='ck_sessions_stage'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('usage_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_user_id'), ['user_id'], unique=False)

    op.create_table('drafts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sentence_map', sa.JSON(), nullable=False),
    sa.Column('lint_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drafts_session_id'), ['session_id'], unique=False)

    op.create_table('outline_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('arc_block', sa.String(length=10), nullable=True),
    sa.Column('label', sa.String(length=40), nullable=True),
    sa.Column('material_ids', sa.JSON(), nullable=False),
    sa.Column('target_chars', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outline_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outline_items_session_id'), ['session_id'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.CheckConstraint("kind IN ('repeated', 'gap', 'skipped', 'hesitation')", name='ck_signals_kind'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_session_id'), ['session_id'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.CheckConstraint("kind IN ('period', 'person', 'place', 'object', 'gap')", name='ck_tags_kind'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_session_id'), ['session_id'], unique=False)

    op.create_table('turns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('input_mode', sa.String(length=10), nullable=True),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("input_mode IS NULL OR input_mode IN ('voice', 'text')", name='ck_turns_input_mode'),
    sa.CheckConstraint("role IN ('user', 'coach')", name='ck_turns_role'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turns_session_id'), ['session_id'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('turn_id', sa.String(length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('arc_block', sa.String(length=10), nullable=True),
    sa.Column('emotion_word', sa.Boolean(), nullable=False),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.CheckConstraint("arc_block IS NULL OR arc_block IN ('scene', 'event', 'meaning', 'present', 'resonance')", name='ck_materials_arc_block'),
    sa.CheckConstraint("type IN ('scene', 'object', 'sense', 'dialogue', 'person', 'fact', 'interpretation', 'time', 'place')", name='ck_materials_type'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materials_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materials_session_id'))

    op.drop_table('materials')
    with op.batch_alter_table('turns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turns_session_id'))

    op.drop_table('turns')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_session_id'))

    op.drop_table('tags')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_session_id'))

    op.drop_table('signals')
    with op.batch_alter_table('outline_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outline_items_session_id'))

    op.drop_table('outline_items')
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drafts_session_id'))

    op.drop_table('drafts')
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_events_created_at'))

    op.drop_table('usage_events')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    op.drop_table('users')
    with op.batch_alter_table('story_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_story_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_story_feedback_created_at'))

    op.drop_table('story_feedback')
    with op.batch_alter_table('llm_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_user_id'))
        batch_op.drop_index(batch_op.f('ix_llm_usage_created_at'))

    op.drop_table('llm_usage')
    with op.batch_alter_table('journey_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journey_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_journey_events_session_id'))
        batch_op.drop_index(batch_op.f('ix_journey_events_created_at'))

    op.drop_table('journey_events')
    # ### end Alembic commands ###
